### ISSUE TITLE
1.1. User Story: Intuitively navigate the site

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#12]
1.1 As a **site user** I can **intuitively navigate the site** so that **the layout of the site is consistent**

## Acceptance Criteria:
* Acceptance Criteria 1: Navbar is the same on all pages
* Acceptance Criteria 2: Footer is the same on all pages
* Acceptance Criteria 3: Pages that use the base template are the same on all pages

## Tasks
- [x] Task 1 - Create a base template
- [x] Task 2 - Add view
- [x] Task 2 - Connect to url
#2
