### ISSUE TITLE
1.5 User story: View the privacy policy

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#16]
1.5 As a **site user** I can **click on the privacy policy link** so that **users can view the privacy policy**

## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on the privacy policy and is redirected to the privacy policy template

## Tasks
- [x] Task 1 - Create template
- [x] Task 2 - Create view
- [x] Task 3 - Connect to url
#2
