### ISSUE TITLE
1.6 User Story: View Terms of use policy

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#17]
1.6 As a **site user** I can **see a view the site's Terms of use policy** so that **users can view the terms of use** 

## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on the site terms and is redirected to the site terms template

## Tasks
- [x] Task 1 - Create template
- [x] Task 2 - Create view
- [x] Task 3 - Connect to url
#2
