### ISSUE TITLE
2.1 User Story: View the home page

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#18]
2.1 As a **site user** I can **view the home page** so that **I can learn more about the website and its purpose**

## Acceptance Criteria:
* Acceptance Criteria 1: User enters the site URL and is redirected to the home page
* Acceptance Criteria 2: User clicks on the home page icon and the home page is displayed

## Tasks
- [x] Task 1 - Create template
- [x] Task 2 - Create view
- [x] Task 3 - Connect to url
#3
