### ISSUE TITLE
3.3 User Story Update my profile

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#24]
3.3 As a **site user** I can **update my profile** so that **employers can see more information about me and i can update my billing address**
## Acceptance Criteria:

* Acceptance Criteria 1: Not logged in user cannot see My profile link in the nav drop down
* Acceptance Criteria 2: Logged in user, can see the My profile link in the nav drop down
* Acceptance Criteria 3: If the username or password is incorrect a flash message is displayed to inform the user to re-enter
* Acceptance Criteria 4: If the user has entered the correct credentials, the user is redirected to the home page

# Tasks
- [x] Task 1 - Create template and style
- [x] Task 2 - Add links to navbar 
- [x] Task 3 - Create view
- [x] Task 4 - Connect to URL
#1
