### ISSUE TITLE
4.1 User Story View room topics

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#31]
4.1 As a **logged-in site user** I can **view the room topics** so I can **select a room of interest**
## Acceptance Criteria:
* Acceptance Criteria 1: Users can select the forum link and redirected to a forum template
* Acceptance Criteria 2: All room topics displayed

## Tasks
- [x] Task 1: Create forum template 
- [x] Task 2: Create view
- [x] Task 3: Create Url
#4
