### ISSUE TITLE
4.2 User story View list of posts by room

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#32]
4.2 As a **logged-in site user** I can **view a list of posts by room** so that **I can select a post that interests me and view user comments**
## Acceptance Criteria:

* Acceptance Criteria 1: Users can select a room from the forum template
* Acceptance Criteria 2: Redirected to post list page with a list of posts filtered by the room topic

## Tasks
- [ ] Task 1: Create post list template 
- [ ] Task 2: Create view
- [ ] Task 3: Create Url
#4
