### ISSUE TITLE
4.4 User Story Post detail

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#34]
4.4 As a **logged-in site user** I can **click on a post** so that **I can read the full article and related comments**

## Acceptance Criteria:

* Acceptance Criteria 1: User is able to click on a post
* Acceptance Criteria 2: Post details are displayed, details include posted by username, created on, title, body, any images and comments

## Tasks
- [ ] Task 1 - Create view
- [ ] Task 2 - Create template
- [ ] Task 3 - connect url
#4
