### ISSUE TITLE
4.5 User Story Create a new post

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#35]
4.5 As a **logged-in site user** I can **create a new post** so that **I can post content on the site for other users to view**

## Acceptance Criteria:

* Acceptance Criteria 1: Users can click to add a new post in the view post list
* Acceptance Criteria 2: The User to complete the form, and upload an image
* Acceptance Criteria 3: The User can click on the post to submit and the post is displayed 
* Acceptance Criteria 4: Flash message displayed  - a new post created successfully
* Acceptance Criteria 5: Non-authenticated users will not be able to create new posts

## Tasks
- [x] Task 1 - Update template Create link to add new post
- [x] Task 2 - Create template for new post
- [x] Task 3 - Create form
- [x] Task 4 - Add s3 bucket functionality for uploading images too
- [x] Task 5- Create view to submit the form
- [x] Task6 - Connect url
- [x] Task 7 - Add flash message functionality 
- [x] Task 8 - Add authentication
#4
