### ISSUE TITLE
4.6 User Story Edit post

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#36]
4.6 As a **logged in site user** I can **edit a post (subject header /text body)** so that I can change the content if required
## Acceptance Criteria:

* Acceptance Criteria 1: Users can see the edit link if they are the owner of the post
* Acceptance Criteria 2: Post details displayed, user can edit information and click submit
* Acceptance Criteria 3: Flash message displayed  -post updated successfully
* Acceptance Criteria 5: Non-authenticated users will not be able to edit a post

## Tasks
- [x] Task 1 - Create template
- [ ] Task 2 - Create the view
- [x] Task 3 - Connect url
#4
