### ISSUE TITLE
4.74 User Story Delete post

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#37]
4.7 As a **logged-in site user** I can **delete a post that I have posted** so that **I can take content off the website**
## Acceptance Criteria:

* Acceptance Criteria 1: Users can see the delete link if they are the owner of the post
* Acceptance Criteria 2: Confirmation page displayed to check if the user would like to delete the post
* Acceptance Criteria 3: Post deleted and comments
* Acceptance Criteria 3: Flash message displayed  -post deleted successfully

## Tasks
- [x] Task 1 - Create template
- [x] Task 2 - Create the view
- [x] Task 3 - Connect url
#4
