### ISSUE TITLE
4.8 User Story Comment on a post

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#38]
4.8 As a **logged-in site user** I can **leave comments on a post** so that **I can take an active role in the forum (be involved in the conversation/express my opinion)**
## Acceptance Criteria:

* Acceptance Criteria 1: Users can see the link reply and click on it if they would like to leave a comment
* Acceptance Criteria 2: If the user clicks on add. A form will be displayed for the user to complete.  The user can enter a comment
* Acceptance Criteria 3: User can click on the button add a comment to post 
* Acceptance Criteria 4: Non-authenticated users will not be able to add comments

## Tasks
- [x] Task 1 - Create template
- [x] Task 2 - Create the view
- [x] Task 3 - Connect url
#4
