### ISSUE TITLE
5.1 User Story Product categories

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#42]
5.1. As a **site user** I can **click on categories to view** so that **i can view courses, mentor programmes and events**
## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on growth hub
* Acceptance Criteria 2: All categories are displayed in the header 
* Acceptance Criteria 3: User clicks on courses and the courses list is displayed

## Tasks
- [ ] Task 1: Create template
- [ ] Task 2: Update view
- [ ] Task 3: Connect Url
#5
