### ISSUE TITLE
5.2. User Story Product detail

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#43]
5.2. As a **site user** I can **click on a product** so I can **view learn more about the product**

## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on a product
* Acceptance Criteria 2: Product detail is displayed

## Tasks
- [x] Task 1: Create template
- [x] Task 2: Update view
- [x] Task 3: Connect Url
#5
