### ISSUE TITLE
5.4 User Story Search products by name

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#45]
5.4. As a **site user** I can **search products by name so I can **view products that interest me**
## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on the search bar and enters "python"
* Acceptance Criteria 2: List of profiles are displayed in ascending alphabetical order by python skill

# Tasks
- [x] Task 1: Update the template
- [x] Task 2: Update the view, create the code to search keywords
- [x] Task 3: Connect URL
#5
