### ISSUE TITLE
5.6 User Story Sort products

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#47]
5.6. As a **site user** I can **sort the products list by category, alphabetically**  so that **i can quickly find the product I seek**
## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on the sort drop-down and selects product Ascending order
* Acceptance Criteria 2: List of products are displayed in ascending order
* Acceptance Criteria 3: User clicks on the sort drop-down and selects Date Descending order
* Acceptance Criteria 4: List of profiles are displayed in descending  order 

# Tasks
- [x] Task 1: Update the template
- [x] Task 2: Update the view, create the code to sort
- [x] Task 3: Connect URL
#5
