### ISSUE TITLE
5.7. User Story View previous orders

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#48]
5.7. As a **logged-in site user** I can **view previous orders** so that **check what orders i have placed**
* Acceptance Criteria 1: User clicks profile, previous orders displayed
* Acceptance Criteria 2: User clicks on an order, order detail is displayed

## Tasks
- [x] Task 1 - Update profile template
- [x] Task 2 - Add view
- [x] Task 3 - Connect to URL
#5
