### ISSUE TITLE
6.1 User Story Basket in Nav bar

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#49]
6.1. As a **site user** I can always see the total price of my basket in the navigation bar so that I know what the total cost will be when on the products page

## Acceptance Criteria:
* Acceptance Criteria 1: User clicks Growth hub, the basket is displayed in the navbar
* Acceptance Criteria 2: User adds a product to the basket, the value is shown under the basket in the navbar

# Tasks
- [x] Task 1: Create the template
- [x] Task 2: Create the view
- [x] Task 3: Connect URL
#6

**Comment by ccarabine** [comment]
completed
