### ISSUE TITLE
7.1 User Story Checkout Review Order

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#53]
7.1. As a **site user** i review my order before i pay so that I can change my mind or proceed with the order
## Acceptance Criteria:
* Acceptance Criteria 1: In checkout template, order summary displayed 
* Acceptance Criteria 2: View basket link displayed if the user wants to change products

# Tasks
- [x] Task 1: Add the template
- [x] Task 2: Add the view
- [ ] Task 2: Create the view
#7
