### ISSUE TITLE
8.2. User Story Employer choose a Subscription model

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#59]
8.2. As a **site user** I can **click on a subscription model** so I can **add choose between 3,6, and 12 months to add to the shopping basket**

## Acceptance Criteria:
* Acceptance Criteria 1: User clicks view subscription models and is redirected to the subscription template
* Acceptance Criteria 2: User clicks on 3 months and the order is added to the basket

# Tasks
- [ ] Task 1: Create the template
- [ ] Task 2: Create the view
- [ ] Task 3: Connect URL
#8
