### ISSUE TITLE
9.1 User Story View profile list

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#61]
9.1. As an **employer site user** I can **click on talent centre** so I can **view profiles that interest me**

## Acceptance Criteria:
* Acceptance Criteria 1: non logged in user clicks on the talent centre, redirected to login page
* Acceptance Criteria 2: Logged in user clicks on the talent centre, redirected to talent centre page
* Acceptance Criteria 3: List of profiles are displayed in ascending alphabetical order by name

# Tasks
- [x] Task 1: Update the template
- [x] Task 2: Update the view,
- [x] Task 4: Connect URL

#9
