### ISSUE TITLE
9.2. User Story Search profile by skill

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#62]
9.2. As an **employer site user** I can **search profiles by skill** so I **can view junior developers**

## Acceptance Criteria:
* Acceptance Criteria 1: User clicks on the search bar and enters "python"
* Acceptance Criteria 2: List of profiles are displayed in ascending alphabetical order by python skill

# Tasks
- [x] Task 1: Update the template
- [x] Task 2: Update the view, create the code to search keywords
- [x] Task 3: Connect URL
- [x] Task 4: Test functionality 
#9
