### ISSUE TITLE
9.4. User Story View answers

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#64]
9.4. As an **employer site user** I can **view questions answered by the developer**  so that **assess their level**

## Acceptance Criteria:
* Acceptance Criteria 1: User on  a profile that interests, Answers to the questions displayed in profile section

# Tasks
- [ ] Task 1: Update the template
- [ ] Task 2: Update the view
- [ ] Task 3: Connect URL
#9
