### ISSUE TITLE
9.5. User Story Download developers CV

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#65]
9.5. As an **employer site user** I can **download a developers CV**  so that **read their experience**

## Acceptance Criteria:
* Acceptance Criteria 1: User on  clicks on download cv, cv is downloaded

# Tasks
- [x] Task 1: Update the template
- [x] Task 2: Update the view
- [x] Task 3: Connect URL
