### ISSUE TITLE
9.6. User Story Contact developer directly

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#66]
9.6. As an **employer site user** I can **Contact a developer directly**  so that **I can contact them about a job**

## Acceptance Criteria:
* Acceptance Criteria 1: User on clicks on contact developer
* Acceptance Criteria 2: Contact form displayed with the hidden field of the developer's email address
* Acceptance Criteria 3: User completes the form, and clicks send
* Acceptance Criteria 4: Developer receives an email

# Tasks
- [x] Task 1: Update the template
- [x] Task 2: Update the view
- [x] Task 3: Connect URL
#9
