### ISSUE TITLE
9.7. User Story View subscription plan

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#67]
9.7. As an **employer site user**, I can **view my plan** so that **I can check when my plan expires on my profile**
## Acceptance Criteria:
* Acceptance Criteria 1: User on clicks on their profile
* Acceptance Criteria 2: Plan displayed with a plan ending date

# Tasks
- [ ] Task 1: Update the template
- [ ] Task 2: Update the view
- [ ] Task 3: Connect URL

#9
