### ISSUE TITLE
10.2 User Story Edit room topic

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#69]
10.2. As a **site admin** I can **update room topic** so that **I can manage the site content**

## Acceptance Criteria:

* Acceptance Criteria 1: Logged in as admin, links displayed edit room
* Acceptance Criteria 2: None admin users, link  not displayed 
* Acceptance Criteria 3: Admin users, Click on edit room, edit room template displayed
* Acceptance Criteria 4: Admin user completes the form and submits
* Acceptance Criteria 5: Success message is displayed and redirected to forum template

# Tasks
- [x] Task 1: Create a template, Create edit link to the product
- [x] Task 2: Create views 
- [x] Task 3: Create URL
#10
