### ISSUE TITLE
10.4 User Story Create Products

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#71]
10.4. As a **site admin** I can **create courses, mentor programmes and events** so that **I can manage the site content**
## Acceptance Criteria:

* Acceptance Criteria 1: Logged in as admin, links displayed add product
* Acceptance Criteria 2: None admin users, link not displayed 
* Acceptance Criteria 3: Admin users, Click on add product, add product template displayed
* Acceptance Criteria 4: Admin user completes the form and submits
* Acceptance Criteria 5: Success message is displayed and redirected to forum template

# Tasks
- [x] Task 1: Create template, Create add link to the product
- [x] Task 2: Create views 
- [x] Task 3: Create url
#10
