### ISSUE TITLE
10.7. User Story Create subscription

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#74]
10.7. As a **site admin** I can **create a subscriptions model and content** so that **I can manage the site content**

## Acceptance Criteria:

* Acceptance Criteria 1: Logged in as admin, links displayed add Subscription
* Acceptance Criteria 2: None admin users, link not displayed 
* Acceptance Criteria 3: Admin users, Click on add subscription, add subscription template displayed
* Acceptance Criteria 4: Admin user completes the form and submits
* Acceptance Criteria 5: Success message is displayed and redirected to subscription template

# Tasks
- [ ] Task 1: Create template, Create add link to the subscription
- [ ] Task 2: Create views 
- [ ] Task 3: Create url
#10
