### ISSUE TITLE
11.1 User Story Error handling templates

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#77]
11.1. As a **site user** who is **directed to a non-existent page or resource**, I can **redirected to the relevant error page**
## Acceptance Criteria:

* Acceptance Criteria 1: Error page displayed

## Tasks
- [x] Task 1 Create views
- [x] Task 2 Create template 400, 403,404, 500
- [x] Task 3 Connect urls
#11
