### ISSUE TITLE
11.2 Non logged in user access

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#78]
11.2. As a **site admin** I want **non-logged users only to have access to the home page, forum home page, no access to talent center, full access to purchase in the E-commerce store**

## Acceptance Criteria:
* Acceptance Criteria 1: None logged in user clicks on the forum and is redirected to the home page
* Acceptance Criteria 2: None logged in user can purchase items successfully
* Acceptance Criteria 3: None logged in user clicks on Talent centre and is redirected to home page

## Tasks

- [x] Task 1 Add the login_required decorator to the relevant methods and/or classes
- [x] Task 2 Add logic in templates to determine whether the user is logged in
- [x] Task 3 Update redirect link in the relevant views to the sign-in page
#11
