### ISSUE TITLE
3.12 User story Register as employer

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#80]
As an employer user, I can register and select I am an employer user so I can view the talent centre

## Acceptance Criteria:

* Acceptance Criteria 1:User clicks on register, redirected talent center

## Tasks
- [x] Task 1 Create the view
- [x] Task 2 Create template
- [ ] Task 3 Connect URL
#1
