### ISSUE TITLE
3.11. USER STORY: Register as a normal user

### ISSUE THREAD

**Issue by ccarabine** [ccarabine/junior-dev-talent#82]
As a user I can register and select I am a normal user so that I can complete my profile

## Acceptance Criteria:

* Acceptance Criteria 1: register and click submit
* Acceptance Criteria 2:redirected to template/modal 
* Acceptance Criteria 3: select normal user
* Acceptance Criteria 4: redirected to edit profile

## Tasks
- [ ] Task 1 Create the view
- [ ] Task 2 Create template
- [ ] Task 3 Connect URL
